# Generated by Django 5.2.12 on 2026-03-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="游戏ID"
                    ),
                ),
                (
                    "global_rank",
                    models.IntegerField(default=0, verbose_name="全球销售排名"),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=500, verbose_name="游戏名称"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        default="", max_length=50, verbose_name="游戏平台"
                    ),
                ),
                (
                    "release_year",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="发行年份"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        default="", max_length=100, verbose_name="游戏类型"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(default="", max_length=500, verbose_name="发行商"),
                ),
                (
                    "publisher_country",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="发行商所属国家",
                    ),
                ),
                (
                    "na_sales",
                    models.FloatField(
                        default=0.0,
                        help_text="单位：百万份",
                        verbose_name="北美地区销量",
                    ),
                ),
                (
                    "eu_sales",
                    models.FloatField(
                        default=0.0,
                        help_text="单位：百万份",
                        verbose_name="欧洲地区销量",
                    ),
                ),
                (
                    "jp_sales",
                    models.FloatField(
                        default=0.0,
                        help_text="单位：百万份",
                        verbose_name="日本地区销量",
                    ),
                ),
                (
                    "other_sales",
                    models.FloatField(
                        default=0.0,
                        help_text="单位：百万份",
                        verbose_name="其他地区销量",
                    ),
                ),
                (
                    "global_sales",
                    models.FloatField(
                        default=0.0, help_text="单位：百万份", verbose_name="全球总销量"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="满分10分", verbose_name="游戏评分"
                    ),
                ),
                (
                    "avg_playtime",
                    models.IntegerField(
                        default=0, help_text="单位：小时", verbose_name="人均游戏时长"
                    ),
                ),
                (
                    "multiplayer",
                    models.BooleanField(default=False, verbose_name="多人模式支持"),
                ),
                (
                    "has_dlc",
                    models.BooleanField(default=False, verbose_name="是否有DLC"),
                ),
                (
                    "media_review",
                    models.CharField(
                        default="", max_length=50, verbose_name="媒体评价"
                    ),
                ),
                (
                    "player_review",
                    models.CharField(
                        default="", max_length=50, verbose_name="玩家口碑"
                    ),
                ),
                (
                    "is_awarded",
                    models.BooleanField(default=False, verbose_name="是否获奖"),
                ),
                (
                    "award_count",
                    models.IntegerField(default=0, verbose_name="获奖数量"),
                ),
                (
                    "language_count",
                    models.IntegerField(default=0, verbose_name="游戏语言数量"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "游戏销售数据",
                "verbose_name_plural": "游戏销售数据",
                "db_table": "game",
                "ordering": ["global_rank"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=255, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=255, verbose_name="密码"),
                ),
                (
                    "sex",
                    models.CharField(default="", max_length=255, verbose_name="性别"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=255, verbose_name="地址"),
                ),
                (
                    "avatar",
                    models.FileField(
                        default="avatar/default.png",
                        upload_to="avatar",
                        verbose_name="头像",
                    ),
                ),
                (
                    "textarea",
                    models.CharField(
                        default="这个人很懒，什么都没写...",
                        max_length=255,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "createTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "前台用户",
                "verbose_name_plural": "前台用户",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="评论ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(default="", max_length=200, verbose_name="用户名"),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="用户头像"
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="评论内容")),
                (
                    "rating",
                    models.FloatField(
                        default=0.0, help_text="1-5分", verbose_name="用户评分"
                    ),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("reply_count", models.IntegerField(default=0, verbose_name="回复数")),
                (
                    "comment_time",
                    models.CharField(
                        default="", max_length=100, verbose_name="评论时间"
                    ),
                ),
                (
                    "comment_timestamp",
                    models.BigIntegerField(default=0, verbose_name="评论时间戳"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "积极"),
                            ("negative", "消极"),
                            ("neutral", "中性"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="情感倾向",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(default=0.0, verbose_name="情感得分"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.game",
                        verbose_name="关联游戏",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏评论",
                "verbose_name_plural": "游戏评论",
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="GameFavorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="收藏备注"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.game",
                        verbose_name="游戏",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏收藏",
                "verbose_name_plural": "游戏收藏",
                "db_table": "game_favorites",
                "ordering": ["-created_time"],
                "unique_together": {("user", "game")},
            },
        ),
    ]
